### ISSUE TITLE
ERROR: 401 - undefined when downloading files

### ISSUE THREAD

**Issue by jbranders** [estruyf/gulp-spsync-creds#10]
When i execute my gulp task "download" i get the 401 undefined error. Everything is correct but it's not working. Can you please tell me what i do wrong? it's on a on premise environment.

**Comment by estruyf** [comment]
Can you turn on verbose logging and see where it fails? This is another property you can add: `verbose: true`.

**Comment by jbranders** [comment]
I don't get the verbose logging working, the only thing i see is this:
![image](https://user-images.githubusercontent.com/16958349/32162667-10828cb2-bd5a-11e7-9eb3-41c14f313d01.png)

**Comment by estruyf** [comment]
@jbranders do you have special characters in your username or password? Have you tried it with another account?

**Comment by jbranders** [comment]
@estruyf  i had a "_" in the name of the folder, so now i renamed the folder in a regular name without any capital letters and it works fine. Thanks!

**Comment by stevebeauge** [comment]
I'm facing the same issue, I guess.

In my node project, I have a `dist` folder that contains a `style library` folder. I want to use the gulp task to copy everything from the `dist` folder to the root of the SharePoint site. That way, I can reflect the exact target structure within my dist folder.

But when I run the task, I get the same error `401 - undefined`.

Full log is:

```
Unhandled rejection StatusCodeError: 401 - undefined
    at new StatusCodeError (C:\Path\To\My\Project\node_modules\sp-request\node_modules\request-promise\lib\errors.js:32:15)
    at Request.RP$callback [as _callback] (C:\Path\To\My\Project\node_modules\sp-request\node_modules\request-promise\lib\rp.js:77:29)
    at Request.self.callback (C:\Path\To\My\Project\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Path\To\My\Project\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Path\To\My\Project\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Thanks in advance

**Comment by estruyf** [comment]
@stevebeauge it could be an issue with the password. Can you please try another user to verify this?

**Comment by stevebeauge** [comment]
Same issue with another user.
Both users I tried are site collection admins, and one is farm admin.

In the passwords, I have characters that contains letters (upper or lowercase, diacritics allowed), numbers and specials characters (a `!` in my test user).

Using Fiddler didn't helped me much to understand.
IIS log files shows two calls to `/_api/contextinfo` that have 401.1 then 401.0 status code.

There's no custom configuration on the WebApp. I can, for example, use CSOM scripts using the same users.

On the server, the LoopbackCheck protection was disabled.

I also tried both locally and remotely on the server.

**Comment by koltyakov** [comment]
@stevebeauge,

Does authentication work for any other user?
It can be that NTLMv2 is used, which is not supported with Node.js auth lib. 

NTLM version can be checked in the [registry key on SP server(s)](https://technet.microsoft.com/en-us/library/cc960646.aspx?f=255&MSPPError=-2147217396).

**Comment by stevebeauge** [comment]
@koltyakov thanks for the tip. However, the key is not present on the server. The default value is then 0 which states 

> Clients use LM and NTLM authentication, but they never use NTLMv2 session security. Domain controllers accept LM, NTLM, and NTLMv2 authentication. 

That said, the Fiddler trace shows:

```
Flags:	0xa208a207
	Unicode supported in security buffer.
	OEM strings supported in security buffer.
	Request server's authentication realm included in Type2 reply.
	NTLM authentication.
	Client workstation name provided.  Server can determine if the client eligible for local authentication.
	Negotiate Always Sign.
	Negotiate NTLM2 Key.
	Supports 56-bit encryption.
	Supports 128-bit encryption.
```

There's a mention to NTLM V2....
