### ISSUE TITLE
Is there a way not to specified password in a plan text config file ?

### ISSUE THREAD

**Issue by jeffangama** [estruyf/gulp-spsync-creds#13]
Is there a way not to specified password in a plan text config file ?

**Comment by koltyakov** [comment]
In local dev scenarios, by using `cpass` for example. ;)

**Comment by estruyf** [comment]
@seaSide974 check: https://www.npmjs.com/package/cpass

@koltyakov good recommendation! Thanks.

**Comment by jeffangama** [comment]
But using Cpass, you still store the password somewhere no  ? in the gulpfile.js ?

**Comment by koltyakov** [comment]
You store it somewhere in the settings - JSON, JS, ENV which is excluded from Git repository, obviously, it should not be in gulpfile.js.

The idea behind cpass is simple: if somebody sees hashed password (i.e. screen sharing) or even gets the hash (i.e. incidental Git commit), he can do nothing with it. The hash can be decoded to raw password only on the machine where it was created.

As an alternative, it could have been Windows Credential Manager used (not cross-platform and dependency installation compilation challenges).

**Comment by jeffangama** [comment]
After researching and because I do not know how to adapt to use Windows Credential Manager or cpass though :/... for my requirement, i'll use https://github.com/wictorwilen/gulp-spsync , which allows to authenticate via clientID and Secret.

**Comment by koltyakov** [comment]
Ok. Just another supported auth strategy among others (SAML, Add-In Only, ADFS, FBA, NTLM, On Demand). ;)

**Comment by jeffangama** [comment]
I think the appID / secret is a good way to authenticate because it works on premise and O365 :)

**Comment by koltyakov** [comment]
I'm saying that Add-In Only auth is one of the [supported](https://github.com/s-KaiNet/node-sp-auth#params) within the SP-Node.js toolchain ecosystem. It's up to your scenario which one to use.
