### ISSUE TITLE
Not uploading all files

### ISSUE THREAD

**Issue by madenorth** [estruyf/gulp-spsync-creds#2]
Hi Elio

Have you seen any situations where this doesn't upload files from subfolders? It uploaded them correctly originally but now it's stopped uploading them. It uploads ones from folders at a higher level and a folder on the same level but is ignoring one folder now.

Happy to pass over any details you wish.

Cheers

Matt

**Comment by estruyf** [comment]
Hi Matt,

So if I understand it correctly, you have a folder structure similar like this:

```
├── src/
│   └── folder1/
│       └── subfolder1/
│       └── subfolder2/
│   └── folder2/
│       └── subfolder3/
```

When you run your gulp task, it only uploads the files from folder1 and folder2. Not from subfolder1, 2 or 3. Is that correct?

What does your gulp task look like?

**Comment by madenorth** [comment]
Hi Elio

No, not quite. I've attached a screenshot of the folder structure, everything is being uploaded except the Views folder and contents. 
![screen shot 2016-09-02 at 09 15 30](https://cloud.githubusercontent.com/assets/19312069/18197213/f4051fa0-70ed-11e6-8ed1-706fd91e8e25.png)

This is the gulp task
`gulp.task("upload",['compile'],function () {
    gulp.src('./App/*_/_')
    .pipe(spsync({
        "username": creds.username,
        "password": creds.password,
        "site": creds.site,
        "verbose": true,
    }))

});`

It doesn't even mention that folder in anywhere in the verbose output.

Cheers

**Comment by estruyf** [comment]
Can you try specifying the following src parameter: gulp.src('.App/*_/_.*')

**Comment by madenorth** [comment]
That doesn't do anything

**Comment by madenorth** [comment]
Just looked at the code above, that's not the right src parameter, it didn't paste properly.
The src property actually I had actually is: `gulp.src('./App/**/*')`

**Comment by estruyf** [comment]
Now I see what happened. I meant to use the following: `gulp.src('./App/**/*.*')`

**Comment by madenorth** [comment]
That seems to work, any reason why it would just ignore one folder the way I had it?

Thanks anyway

**Comment by estruyf** [comment]
@oozoo-solutions if you use `gulp.src('./App/**/*')` it will also pass the folders to the stream. By changing it to this `gulp.src('./App/**/*.*')` it will only take files.

Running with `gulp.src('./App/**/*')`
![snip_20160902115758](https://cloud.githubusercontent.com/assets/2900833/18200321/945f49f6-7104-11e6-8be9-f7377796f49e.png)

Running with `gulp.src('./App/**/*.*')`
![snip_20160902115823](https://cloud.githubusercontent.com/assets/2900833/18200337/a28d0f7c-7104-11e6-9ba9-89cd764e571f.png)

I will take a look at the code to see if I can implement a catch for folders.

**Comment by madenorth** [comment]
Great thanks.
