### ISSUE TITLE
Images downloaded from Sharepoint are corrupted

### ISSUE THREAD

**Issue by SamiSaves** [estruyf/gulp-spsync-creds#4]
Hello again!

I downloaded images with the download function and all the image files turned out corrupted. Is this method only meant for the display templates and other code files?

I tried to download the images from style library and then tried downloading some default images from path "_catalogs/masterpage/en-us". Both gave me the same corrupted images.

**Comment by estruyf** [comment]
Should be fixed with the new update that has just been pushed. Problem was encoding of the retrieved file body.

**Comment by SamiSaves** [comment]
Thanks again for the quick fix! I can test this on monday, and I'll let you know how it goes.

**Comment by SamiSaves** [comment]
The images were downloaded successfully. I'll close this issue.

**Comment by estruyf** [comment]
@SamiEklund thanks for the feedback and testing.
