### ISSUE TITLE
Not uploading all content

### ISSUE THREAD

**Issue by madenorth** [estruyf/gulp-spsync-creds#5]
Hi @estruyf 

Came across the issue where it's not uploading all the files again. All the build and file are in this repository. 

https://github.com/lccgov/lcc_whatson_events

If you clone it and do a gulp build it will try and upload all the files. 
At my end it does most of the images folder then stops.
You will also need to remove json from the blocked files list in Central Admin

Thanks, Matt

**Comment by madenorth** [comment]
Sorry @estruyf I've managed to get to the bottom of the this, return was missing from the task

**Comment by estruyf** [comment]
Great you found the problem. Thanks
