### ISSUE TITLE
password with ( or ) not supported?

### ISSUE THREAD

**Issue by Jaapieo** [estruyf/gulp-spsync-creds#8]
Hi Elio, 

I'm using the gulp-spsync-creds in a few projects and I was trying to download theme files from different customers. Works great, but with 2 customer i got the message "[09:52:50] No files found on the specified startFolder path". Using the same code (startpath: "_catalogs/theme/15/") on other customers gives no trouble at all. The only difference between the 2customer that doens't work and the ones that do work are that the passwords contain a ( or ).
could that be the problem?

Greetings Jaap

**Comment by estruyf** [comment]
Hi @Jaapieo,

Just tested this with a new user which contains a couple of symbols in the password like `()`, but works without any issues. To be sure I pushed a new version that should return the error message. Can you install the latest version on your machine and test it again?

Thanks,
Elio

**Comment by Jaapieo** [comment]
Hi Elio,

Thanks for the quick response, the error message is:
"ERROR: Direct login to WLID is not allowed for this federated namespace"
So I think it is something with the configuration of the O365 environment.

Also thanks for this nice gulp packege, I'm using it quite often :)

ps. dit kan toch ook in het nederlands?

greetings Jaap

**Comment by estruyf** [comment]
Dat kan zeker!

Je maakt gebruik van een AD user (gekoppeld met ADFS). Jammer genoeg is dit niet mogelijk dan. Wat een oplossing zou kunnen zijn is gebruik maken van een Office 365 gebruiker. Mocht dit natuurlijk mogelijk zijn?

**Comment by Jaapieo** [comment]
Oke, helder.
Uiteindelijk heb ik het handmatig gedaan voor deze 2 klanten. Aangezien ik
voor de meeste klanten het automatisch kon doen had ik zoveel tijdswinst
dat die 2 ook niet uitmaakte ;)
Ik zag alleen een overeenkomst in die passwords, dus vandaar dat ik dacht
dat het misschien aan die tekens lag, maar dat blijkt dus duidelijk van
niet.

Bedankt iig voor de snelle reactie en natuurlijk de ontwikkeling van de
plugin :)

groeten Jaap

2017-04-07 14:22 GMT+02:00 Elio Struyf <notifications@github.com>:

**Comment by estruyf** [comment]
Ik ben nog even bezig met het bekijken van een bepaalde dependency. Kan zijn dat het opgelost is met een nieuwe update. Ik breng deze zo meteen uit.

**Comment by Jaapieo** [comment]
Top! Als je iets hebt, laat maar weten dan test ik wel even

2017-04-07 14:30 GMT+02:00 Elio Struyf <notifications@github.com>:

**Comment by estruyf** [comment]
Ok, nieuwe versie is nu online. Best even de volledige node_modules folder verwijderen en terug de dependencies laten installeren `npm install`. Dan weet je dat je zeker de laatste hebt.

**Comment by Jaapieo** [comment]
Nice, works like a charm!

Alle bestanden binnen gehaald

groeten Jaap

**Comment by estruyf** [comment]
Super!

Niet alleen mijn werk, lag ook aan de dependencies.
