### ISSUE TITLE
Uploading more than 10 files does not work

### ISSUE THREAD

**Issue by dhavalshah01** [estruyf/gulp-spsync-creds#9]
Hi,

I am trying to upload around 50 files in SharePoint Document library but looks like the code get terminated because of async. It works for 10-15 files and then throws this error.

![image](https://user-images.githubusercontent.com/13947393/29717453-d68ad5aa-8974-11e7-9ab1-b76cff36a9e2.png)

About to exit with code: 0
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

Anybody Facing this issue ?

**Comment by estruyf** [comment]
I could reproduce the same error on my environment and I think I found a fix for the problem which is working on my environment. Can you try the latest gulp-spsync-creds version by installing it: `npm install gulp-spsync-creds@latest --save-dev`.

**Comment by dhavalshah01** [comment]
I am  still facing the issue, especially when we package it using the sp-client-custom-fields which generate more than 20 resources string files in the bundle. Uploading these files still gives the time out error.

**Comment by estruyf** [comment]
I try again to reproduce it again, as I tried it without issues about 50 files already. Can you give a bit more info about the type of files and sizes?

**Comment by estruyf** [comment]
Just did another batch of test runs and cannot to seem to reproduce the issue you encounter. 

<img width="280" alt="screenshot 2017-09-15 09 19 12" src="https://user-images.githubusercontent.com/2900833/30470971-2b63d5ee-99f7-11e7-8dcc-d2539d93df5a.png">

Would you be able to debug the task to check out where it might go wrong?

**Comment by dhavalshah01** [comment]
I have observed that it works when the files are uploaded second time (when we are replacing existing files) But when we upload it first time it gives the above error.

I think the problem could be with the folder sub hierarchy

We are uploading the files in the folder with 3 level deep hieararchy. Something like this,
WebpartName --> Environment Name --> DeveloperName

And inside the DeveloperName folder we are uploading the files.

**Comment by estruyf** [comment]
Thanks for the information. Just did another set of test runs, but still no issues on my side. 

Just to be 100% sure, can you check the code of the `gulp-spsync-creds` module in your `node_modules` folder. Just to know that it is the latest version it retrieved.

In the `index.js` file you should see a `fileDone` function. Which one do you have:

**Option 1**
```JavaScript
var fileDone = function (parameter) {
  cb(null, file);
}
```

**Option 2**
```JavaScript
var fileDone = function (parameter) {
  cb();
}
```

**Comment by dhavalshah01** [comment]
I see option 2.

**Comment by estruyf** [comment]
Ok, so that is already good. 

Just uploaded a new version: gulp-spsync-creds@2.3.7

I added additional logging to it if something fails. Can you test it out and also can you set the `verbose` property to `true`, that way we can see all the request outcomes?

If it fails once more, you should be able to see the last step, hopefully, that gives us a clue.

**Comment by dhavalshah01** [comment]
So i tried out updating the package and looks like still there is an error. Below is a screenshot.

![image](https://user-images.githubusercontent.com/13947393/31523029-b541d3b2-af76-11e7-8089-286b7745adc1.png)

**Comment by estruyf** [comment]
So apparently you get a timeout connecting to SharePoint? Do you always get it at the same point?
